#!/bin/sh
#
# Start server to communicate with client.
#

start() {
        /usr/debugging-files/target-server &
}

stop() {
        pkill -f "/usr/debugging-files/target-server"
}

restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?


